<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '6f28ce70255065daf72d569509f5d169',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/taptima',
);
