#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#Library_crud:
#  path: /
#  controller: App\Controller\BooksController::index

Add_book:
  path: /
  controller: App\Controller\BooksController::writeData