blog_list:
  path: /
  controller: App\Controller\BooksController::readData

WriteBook:
  path: /add
  controller: App\Controller\BooksController::writeData

form:
  path: /form
  controller: App\Controller\BooksController::index