#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#Library_crud:
#  path: /
#  controller: App\Controller\BooksController::index

GetAllBooks:
  path: /
  controller: App\Controller\BooksController::readData
WriteBook:
  path: /ajax/add_book
  controller: App\Controller\BooksController::writeData