blog_list:
  path: /
  controller: App\Controller\BooksController::readData

WriteBook:
  path: /add
  controller: App\Controller\BooksController::writeData

form:
  path: /form
  controller: App\Controller\BooksController::formAdd

updateData:
  path: /update
  controller: App\Controller\BooksController::updateData

deleteBook:
  path: /deletebook
  controller: App\Controller\BooksController::deleteBook

readAutors:
  path: /getauthors
  controller: App\Controller\AuthorController::readData

formAutors:
  path: /formautors
  controller: App\Controller\AuthorController::formAdd

addAuthors:
  path: /addauthors
  controller: App\Controller\AuthorController::addAuthors

updateEventListener:
  path: /updateevent
  controller: App\Controller\AuthorController::updateEventListener

deleteAuthors:
  path: /deleteauthor
  controller: App\Controller\AuthorController::deleteAuthor

updateDataAuthor:
  path: /updateAuthor
  controller: App\Controller\AuthorController::updateAuthor

