<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3m28Rpd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3m28Rpd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3m28Rpd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3m28Rpd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3m28Rpd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3m28Rpd',
    'container.build_id' => '3e2ff0c5',
    'container.build_time' => 1638587562,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3m28Rpd');
