<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'blog_list' => [[], ['_controller' => 'App\\Controller\\BooksController::readData'], [], [['text', '/']], [], []],
    'WriteBook' => [[], ['_controller' => 'App\\Controller\\BooksController::writeData'], [], [['text', '/add']], [], []],
    'form' => [[], ['_controller' => 'App\\Controller\\BooksController::formAdd'], [], [['text', '/form']], [], []],
    'updateData' => [[], ['_controller' => 'App\\Controller\\BooksController::updateData'], [], [['text', '/update']], [], []],
    'updateImage' => [[], ['_controller' => 'App\\Controller\\BooksController::updateImage'], [], [['text', '/updateimage']], [], []],
    'deleteBook' => [[], ['_controller' => 'App\\Controller\\BooksController::deleteBook'], [], [['text', '/deletebook']], [], []],
    'readAutors' => [[], ['_controller' => 'App\\Controller\\AuthorController::readData'], [], [['text', '/getauthors']], [], []],
    'formAutors' => [[], ['_controller' => 'App\\Controller\\AuthorController::formAdd'], [], [['text', '/formautors']], [], []],
    'addAuthors' => [[], ['_controller' => 'App\\Controller\\AuthorController::addAuthors'], [], [['text', '/addauthors']], [], []],
    'updateEventListener' => [[], ['_controller' => 'App\\Controller\\AuthorController::updateEventListener'], [], [['text', '/updateevent']], [], []],
    'deleteAuthors' => [[], ['_controller' => 'App\\Controller\\AuthorController::deleteAuthor'], [], [['text', '/deleteauthor']], [], []],
    'updateDataAuthor' => [[], ['_controller' => 'App\\Controller\\AuthorController::updateAuthor'], [], [['text', '/updateAuthor']], [], []],
];
